In [1]:
import pandas as pd
student_csv_pd = ("Resources/students_complete.csv")
student_data =pd.read_csv(student_csv_pd)

school_csv_pd =("Resources/schools_complete.csv")
school_data= pd.read_csv(school_csv_pd)

# Combine the data into a single dataset
stu_sch_data= pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])

In [2]:
###DISTRICT SUMMARY###
#Answer metrics with no Frame

#Total Schooos
total_schools=school_data["School ID"].count()

#Total Students
total_students=student_data["Student ID"].count()

#Total Budget
total_budget=school_data["budget"].sum()

#Cost per Student
per_student_budget=total_schools/total_budget

In [3]:
### Create Bins and create new columns with Pass/Fail
reading_bins=[0,69,100]
math_bins=[0,69,100]
overall_bins=[0,69,100]

#Labels
group_names=["Fail","Pass"]
Pass_name=[0,1]

###### Pass / Fail Module  ########

#Reading Pass/Fail and Pass Count
stu_sch_data["Reading Pass/Fail"]=pd.cut(stu_sch_data["reading_score"],reading_bins,labels=group_names)
stu_sch_data["Reading Pass Count"]=pd.cut(stu_sch_data["reading_score"],reading_bins,labels=Pass_name)
stu_sch_data["Reading Pass Count"]=stu_sch_data["Reading Pass Count"].astype('float64')


##Math Pass/Fail and Pass Count
stu_sch_data["Math Pass/Fail"]=pd.cut(stu_sch_data["math_score"],math_bins,labels=group_names)
stu_sch_data["Math Pass Count"]=pd.cut(stu_sch_data["math_score"],math_bins,labels=Pass_name)
stu_sch_data["Math Pass Count"]=stu_sch_data["Math Pass Count"].astype('float64')

In [15]:
#All Schools(tot)SCORE:Total Math,Reading with TOTAL avg Math and reading

#Total Math Scores
total_math_scores=stu_sch_data["math_score"].sum()
tot_avg_math_score=total_math_scores/total_students
stu_sch_data['Tot_Avg_Math']=tot_avg_math_score

#Total Reading Scores
total_read_scores=stu_sch_data["reading_score"].sum()
tot_avg_read_score=total_read_scores/total_students
stu_sch_data['Tot_Avg_Read']=tot_avg_read_score

#Percentage of students that passed math
total_math_pass=stu_sch_data.loc[stu_sch_data["Math Pass/Fail"]=="Pass","Math Pass/Fail"]
count_math_pass=total_math_pass.count()
tot_pct_math_pass=(count_math_pass/total_students)*100
stu_sch_data['Tot_Math_Pct_Pass']=tot_pct_math_pass

#Percentage of students that passed Reading
total_read_pass=stu_sch_data.loc[stu_sch_data["Reading Pass/Fail"]=="Pass","Reading Pass/Fail"]
count_read_pass=total_read_pass.count()
tot_pct_read_pass=(count_read_pass/total_students)*100
stu_sch_data['Tot_Pct_Pass']=tot_pct_read_pass

#Overall_pass
tot_pct_overeall_pass=(tot_pct_math_pass+ tot_pct_read_pass)/2
stu_sch_data['Tot_Overall_Pass_rate']=tot_pct_overeall_pass

In [5]:
######################################################         ANSWER 1             ####################################

#Set up summary Dataframe to print metrics from above
Answer1_df=pd.DataFrame({"Total Schools":[total_schools],"Total Students":[total_students],"Total Budget":[total_budget],
                      "Average Math Score":[tot_avg_math_score],"Average Reading Score":[tot_avg_read_score],
                      "% Passing Math":[tot_pct_math_pass],"% Passing Reading":[tot_pct_read_pass],
                       "Overall_Pass_rate":[tot_pct_overeall_pass]})

Answer1_df["Total Students"] = Answer1_df["Total Students"].astype(float).map("{:,.0f}".format)
Answer1_df["Total Budget"] = Answer1_df["Total Budget"].astype(float).map("${:,.2f}".format)
Answer1_df

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,Overall_Pass_rate
0,15,"39,170","$24,649,428.00",78.985371,81.87784,74.980853,85.805463,80.393158

In [13]:
Answer2_base=stu_sch_data[["school_name","type","reading_score","Reading Pass/Fail","Reading Pass Count", 
                     "math_score","Math Pass/Fail", "Math Pass Count","size", "budget","Student ID"]]

In [12]:
Answer2_grpby=Answer2_base.groupby(["school_name","type"])
Answer2_grpby_sum=Answer2_grpby.sum()
Answer2_grpby_sum

,,reading_score,Reading Pass Count,math_score,Math Pass Count,size,budget,Student ID
school_name,type,,,,,,,
Bailey High School,District,403225,4077.0,383393,3318.0,24760576,15549641728,101303896
Cabrera High School,Charter,156027,1803.0,154329,1749.0,3452164,2009159448,31477307
Figueroa High School,District,239335,2381.0,226223,1946.0,8696601,5557128039,12949059
Ford High School,District,221164,2172.0,211184,1871.0,7502121,4831365924,99055935
Griffin High School,Charter,123043,1426.0,122360,1371.0,2155024,1346890000,19077394
Hernandez High School,District,375131,3748.0,358238,3094.0,21483225,14007062700,46090440
Holden High School,Charter,35789,411.0,35784,395.0,182329,105933149,9846620
Huang High School,District,236810,2372.0,223528,1916.0,8508889,5573322295,4252986
Johnson High School,District,385481,3867.0,366942,3145.0,22667121,14733628650,154327815
Pena High School,Charter,80851,923.0,80654,910.0,925444,563595396,22851829
Rodriguez High School,District,322898,3208.0,307294,2654.0,15992001,10186904637,112111965
Shelton High School,Charter,147441,1688.0,146796,1653.0,3101121,1860672600,11879706
Thomas High School,Charter,137093,1591.0,136389,1525.0,2673225,1705517550,62705520
Wilson High School,Charter,191748,2204.0,190115,2143.0,5212089,3012587442,33950493
Wright High School,Charter,151119,1739.0,150628,1680.0,3240000,1888920000,45243900